version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports:
      - '3000:3001'
#Services is represented as a type of container
#'-' in a yml file specifies an array
# NB: the first port is the local machine while the other is the docker port.
# Read on restart policy => restart: always
